version: '3'
services:
  cff-chart-prototype:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    env_file:
      - .env
